import os

SONET_ENVIRONMENT = os.getenv('NEWSAI_SONET_ENVIRONMENT', '')
SONET_TWTR_CONSUMER_KEY = os.getenv('NEWSAI_SONET_TWTR_CONSUMER_KEY', '')
SONET_TWTR_CONSUMER_SECRET = os.getenv('NEWSAI_SONET_TWTR_CONSUMER_SECRET', '')
SONET_TWTR_ACCESS_TOKEN = os.getenv('NEWSAI_SONET_TWTR_ACCESS_TOKEN', '')
SONET_TWTR_ACCESS_TOKEN_SECRET = os.getenv(
    'NEWSAI_SONET_TWTR_ACCESS_TOKEN_SECRET', '')
CONTEXT_API_USERNAME = os.getenv('NEWSAI_CONTEXT_API_USERNAME', '')
CONTEXT_API_PASSWORD = os.getenv('NEWSAI_CONTEXT_API_PASSWORD', '')
