import os

SONET_ENVIRONMENT = os.getenv('NEWSAI_SONET_ENVIRONMENT', '')
SONET_MONGO_USER = os.getenv('NEWSAI_SONET_MONGO_USER', '')
SONET_MONGO_PASSWORD = os.getenv('NEWSAI_SONET_MONGO_PASSWORD', '')
